name: Build/release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - uses: Yan-Jobs/action-electron-builder@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          max_attempts: 3
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
